export const SELECT_POINTER_REPOSITORY = 'SELECT_POINTER_REPOSITORY'
export const FETCH_ISSUES = 'FETCH_ISSUES'
export const PAGINATION_HANDLE = 'PAGINATION_HANDLE'
export const PER_PAGE_HANDLE = 'PER_PAGE_HANDLE'